---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.241
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 8080
  selector:
    service: ambassador
