apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.1.4:3260
    portals: ['192.168.1.4:3260']
    iqn: iqn.1991-05.com.microsoft:bmf-keycloakdb-target
    lun: 0
    fsType: 'ext4'
    readOnly: false

