---
apiVersion: v1
kind: Service
metadata:
  name: lv-www-router
  namespace: lyfevest
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: lv_www_std_mapping
      regex_headers:
        user-Agent: "^.*Lyfevest.*$"
      prefix: /lvwww/
      service: http://lv-www-std.lyfevest
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: lv_www_cs_mapping
      prefix: /lvwww/
      service: http://lv-www-cs.lyfevest
spec:
  ports:
  - name: http-lv-www
    port: 80
