---
apiVersion: v1
kind: Service
metadata:
  name: "lv-www-cs"
  namespace: lyfevest
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: "lyfevest-coming-soon"
