---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "lyfevestio-www"
  namespace: lyfevest
  labels:
    app: "lyfevestio-www"
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.lyfevestio-www: glob:0.*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "lyfevestio-www"
  template:
    metadata:
      labels:
        app: "lyfevestio-www"
    spec:
      containers:
      - name: "lyfevestio-www"
        image: "lyfevest/lyfevestio-www:0.16.1"
        ports:
        - name: http
          containerPort: 80
