---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "lyfevestio-api"
  namespace: "lyfevest"
  labels:
    app: "lyfevestio-api"
  annotations:
    flux.weave.works/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "lyfevestio-api"
  template:
    metadata:
      labels:
        app: "lyfevestio-api"
    spec:
      containers:
      - name: "lyfevestio-api"
        image: "gcr.io/lyfevest-io-prod-73019/github.com/lyfevest/lyfevestio-api:3d4f2a1"
        ports:
        - name: http
          containerPort: 80
        env:
        - name: DB_USER
          value: lvruntime-beta
        - name: DB_SCHEMA
          value: lyfevest-beta
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lyfevest-secrets
              key: db-password
        - name: RECAPTCHA_SECRET
          valueFrom:
            secretKeyRef:
              name: lyfevest-secrets
              key: recaptcha-secret
        - name: KEYCLOAK_CONFIG
          value: keycloak-beta.json
        - name: KEYCLOAK_API_SECRET
          valueFrom:
            secretKeyRef:
              name: lyfevest-secrets
              key: keycloak-api-secret
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: lyfevest-secrets
              key: keycloak-client-secret
        - name: LV_API_HOST
          value: api.beta.lyfevest.io
        - name: LV_AUTH_HOST
          value: beta.lyfevest.io
        - name: LV_URL
          value: https://beta.lyfevest.io
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lyfevest-secrets
              key: smtp-password
        - name: STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              name: lyfevest-secrets
              key: stripe-api-key
        - name: STRIPE_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: lyfevest-secrets
              key: stripe-public-key
        - name: STRIPE_WH_ALL_SECRET
          valueFrom:
            secretKeyRef:
              name: lyfevest-secrets
              key: stripe-wh-all-secret
        - name: PAYONEER_PROGRAM_ID
          value: "100121370"
        - name: PAYONEER_API_URL
          value: https://api.sandbox.payoneer.com/v2/programs/
        - name: PAYONEER_USERNAME
          valueFrom:
            secretKeyRef:
              name: lyfevest-secrets
              key: payoneer-username
        - name: PAYONEER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lyfevest-secrets
              key: payoneer-password
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: "lyfevestio-api"
  namespace: lyfevest
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: "lyfevestio-api"
  type: LoadBalancer
  loadBalancerIP: 192.168.1.245
