---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "lyfevestio-www"
  namespace: lyfevest
  labels:
    app: "lyfevestio-www"
  annotations:
    flux.weave.works/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "lyfevestio-www"
  template:
    metadata:
      labels:
        app: "lyfevestio-www"
    spec:
      containers:
      - name: "lyfevestio-www"
        image: "gcr.io/lyfevest-io-prod-73019/github.com/lyfevest/lyfevestio-www:94f7659"
        ports:
        - name: http
          containerPort: 80
      imagePullSecrets:
      - name: regcred
