---
apiVersion: v1
kind: Service
metadata:
  name: "lyfevestio-www"
  namespace: lyfevest
spec:
  ports:
  - name: http
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
#    app: "lyfevestio-www"
     app: "lyfevest-coming-soon"
  type: LoadBalancer
  loadBalancerIP: 192.168.1.243
