apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go 
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/qodfathr/helloworld-go:1.0
            env:
              - name: TARGET 
                value: "Go Sample v1.0"

