apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
  labels:
    app: ghost
spec:
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.1.4:3260
    portals: ['192.168.1.4:3260']
    iqn: iqn.1991-05.com.microsoft:bmf-k8s-target
    lun: 1
    fsType: 'ext4'
    readOnly: false

