kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ghost-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 90Gi
  selector:
    matchLabels:
      app: "ghost"
