apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
  namespace: stk
  labels:
    app: ghost
spec:
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteMany
  iscsi:
    targetPortal: 192.168.1.4:3260
    portals: ['192.168.1.4:3260']
    iqn: iqn.1991-05.com.microsoft:bmf-ghost-stk-target
    lun: 0
    fsType: 'ext4'
    readOnly: false

