apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ghost-stk 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-stk 
  template:
    metadata:
      labels:
        app: ghost-stk
    spec:
      containers:
      - name: ghost-stk
        image: ghost:1.24
        ports:
        - name: http
          containerPort: 2368
        env:
        - name: url
          value: https://stufftoddknows.com
        volumeMounts:
        - mountPath: "/var/lib/ghost/content"
          name: ghost-stk-vol
      volumes:
        - name: ghost-stk-vol
          persistentVolumeClaim:
            claimName: ghost-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ghost-stk
spec:
  ports:
  - name: http
    port: 3001
    protocol: TCP
    targetPort: 2368
  selector:
    app: ghost-stk
  type: LoadBalancer
  loadBalancerIP: 192.168.1.242
